# Generated by Django 6.0.3 on 2026-06-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_pal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='price per unit', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='track_pal.warehouse'),
        ),
    ]
