# Generated by Django 6.0.3 on 2026-06-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_pal', '0002_product_pricing_product_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='Location',
            new_name='location',
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
