# Generated by Django 6.0.5 on 2026-06-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_pal', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pricing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cost price per unit', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SellableProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='price you sell this finished product for', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellable_products', to='track_pal.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text="how much of this ingredient, in the ingredient's own unit", max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='track_pal.product')),
                ('sellable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='track_pal.sellableproduct')),
            ],
        ),
    ]
