# Generated by Django 6.0.5 on 2026-06-10 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_pal', '0007_alter_warehouse_stock_quantity_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellableproduct',
            name='finished_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellable_source', to='track_pal.product'),
        ),
    ]
