# Generated by Django 6.0.5 on 2026-06-11 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_pal', '0008_sellableproduct_finished_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('incoming', 'Incoming (from supplier)'), ('outgoing', 'Outgoing (to customer)')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('party', models.CharField(blank=True, help_text='supplier name (incoming) or customer name (outgoing)', max_length=150, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_method', models.CharField(blank=True, choices=[('sea', 'Sea'), ('ground', 'Ground'), ('air', 'Air')], max_length=10, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('truck', 'Truck'), ('ship', 'Ship'), ('plane', 'Plane'), ('container', 'Container')], max_length=12, null=True)),
                ('vehicle_count', models.PositiveIntegerField(blank=True, help_text='number of trucks / ships / containers', null=True)),
                ('carrier', models.CharField(blank=True, help_text='shipping company', max_length=150, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=120, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('stock_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='track_pal.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='track_pal.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='track_pal.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
