# Generated by Django 6.0.5 on 2026-06-11 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_pal', '0009_stockorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_sales_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='track_pal.warehouse'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, help_text='table number, customer, etc.', max_length=200, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='sum of line selling prices', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='track_pal.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='where ingredients were deducted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='track_pal.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='selling price at time of sale', max_digits=10, null=True)),
                ('tracked', models.BooleanField(default=False, help_text='were ingredients deducted?')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='track_pal.sale')),
                ('sellable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='track_pal.sellableproduct')),
            ],
        ),
    ]
