# Generated by Django 6.0.5 on 2026-06-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_pal', '0010_company_default_sales_warehouse_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('employee', 'Employee')], default='owner', max_length=10),
        ),
    ]
